version: 0.2
phases:
  install:
    # runtime-versions:
      # nodejs: 16
    commands:
      - echo "Installing dependencies..."
      - npm install
      - npx create-react-app my-app
  build:
    commands:
      - echo "Building React project..."
      - npm run build
  post_build:
    commands:
      - echo "Updating files in the S3 bucket..."
      - aws s3 sync dist/github-s3-01/ s3://my.example.s3.bucket21 --delete


